[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.15
  adafruit/Adafruit SSD1306@^2.5.10
  adafruit/Adafruit GFX Library@^1.11.11
  adafruit/Adafruit NeoPixel@^1.12.2
  mobizt/Firebase ESP32 Client@^4.4.14
build_flags = 
  -I include
  -D WIFI_SSID=\"${sysenv.WIFI_SSID}\"
  -D WIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD}\"
  -D FIREBASE_API_KEY=\"${sysenv.FIREBASE_API_KEY}\"
  -D FIREBASE_DATABASE_URL=\"${sysenv.FIREBASE_DATABASE_URL}\"
